# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions" # Specifies that Dependabot should check for updates to GitHub Actions
    directory: "/" # Location of package manifests (workflows are typically in .github/workflows/)
    schedule:
      interval: "weekly" # How often to check for updates
    # You can add reviewers or assignees for Dependabot PRs if needed
    # reviewers:
    #   - "your-github-username"
    # assignees:
    #   - "your-github-username"
    # commit-message:
    #   prefix: "chore" # Optional: prefix for commit messages
    #   include: "scope" # Optional: include scope in commit messages

# You could add other package ecosystems if your project evolves, for example:
# - package-ecosystem: "npm"
#   directory: "/" # Assuming package.json is in the root
#   schedule:
#     interval: "weekly"
